name: Tic-tac-toe CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  APP_ENV: test
  DATABASE_URL: "postgresql://tester_user:password@localhost:5432/tictactoe?serverVersion=16&charset=utf8"

jobs:
  validate-composer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
      - run: composer validate --strict --no-check-all --no-check-publish

  unit-tests:
    needs: validate-composer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: pcov
      - uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
      - run: composer install --prefer-dist --no-progress
      - run: php ./vendor/bin/phpunit --testsuite Unit

  integration-tests:
    needs: validate-composer
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: tictactoe
          POSTGRES_PASSWORD: password
          POSTGRES_USER: tester_user
        ports: [5432:5432]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo_pgsql
      - uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
      - run: composer install --prefer-dist --no-progress
      - name: Test PostgreSQL connection
        run: |
          run: PGPASSWORD=password psql -h localhost -U tester_user -d tictactoe -c "SELECT 1"
      - run: |
          php bin/console doctrine:database:create --if-not-exists --env=test
          php bin/console doctrine:schema:create --env=test
      - run: php ./vendor/bin/phpunit --testsuite Integration